version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: "lab4-database"
    environment:
      - POSTGRES_DB=weblab4_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: "backend"
    ports:
      - '1260:1260'
    depends_on:
      - db
    environment:
      - DB_URL
      - DB_USER
      - DB_PASSWORD
  frontend:
    build: ./frontend
    container_name: "frontend"
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  db_data: